# Generated by Django 5.1.7 on 2025-03-28 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='transaction',
            name='unique_active_checkout',
        ),
    ]
