# Generated by Django 5.1.7 on 2025-04-04 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_due_date_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 21, 24, 47, 621161, tzinfo=datetime.timezone.utc)),
        ),
    ]
