# Generated by Django 5.1.7 on 2025-03-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='General', max_length=50),
            preserve_default=False,
        ),
    ]
