# Generated by Django 5.1.7 on 2025-03-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='is_librarian',
            field=models.BooleanField(default=False),
        ),
    ]
