# Generated by Django 5.1.7 on 2025-03-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_librarian_is_librarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('librarian', 'Librarian')], default='student', max_length=10),
        ),
    ]
