# Generated by Django 5.1.7 on 2025-03-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarian',
            name='is_librarian',
        ),
    ]
