# Generated by Django 5.1.7 on 2025-03-28 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_remove_librarian_is_librarian'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_approved',
        ),
    ]
